Name: Product
Host: 0.0.0.0
Port: 8001

ProductRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: product.rpc
  # NonBlock: true

Mysql:
  DataSource: root:root@tcp(127.0.0.1:3306)/gozero_mall?charset=utf8mb4&parseTime=true&loc=Local

CacheRedis:
- Host: 127.0.0.1:6379
  Type: node
  Pass: "123456"

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

Telemetry:
  Name: product.api
  Endpoint: http://192.168.11.20:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger