// Code generated by goctl. DO NOT EDIT.
// Source: pay.proto

package server

import (
	"context"

	"go-zero-mall/service/pay/rpc/internal/logic"
	"go-zero-mall/service/pay/rpc/internal/svc"
	"go-zero-mall/service/pay/rpc/pb/pay"
)

type PayServiceServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedPayServiceServer
}

func NewPayServiceServer(svcCtx *svc.ServiceContext) *PayServiceServer {
	return &PayServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------pay-----------------------
func (s *PayServiceServer) AddPay(ctx context.Context, in *pay.AddPayReq) (*pay.AddPayResp, error) {
	l := logic.NewAddPayLogic(ctx, s.svcCtx)
	return l.AddPay(in)
}

func (s *PayServiceServer) GetPayById(ctx context.Context, in *pay.DetailReq) (*pay.DetailResp, error) {
	l := logic.NewGetPayByIdLogic(ctx, s.svcCtx)
	return l.GetPayById(in)
}

func (s *PayServiceServer) Callback(ctx context.Context, in *pay.CallbackReq) (*pay.CallbackResp, error) {
	l := logic.NewCallbackLogic(ctx, s.svcCtx)
	return l.Callback(in)
}
